In [1]:
import pandas as pd
import re

from IPython.display import Image
from pyvirtualdisplay import Display

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import InvalidArgumentException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import csv
import time
import random
from time import sleep

In [2]:
import requests
import csv
#from bs4 import BeautifulSoup
import os
import urllib
import re
#import html5lib
import random
from unicodedata import normalize

In [ ]:
# 삼성 https://web.joongna.com/search?category=1193&saleYn=SALE_Y&page={i}&productFilterType=APP
# 애플 https://web.joongna.com/search?category=1194&page={page}&saleYn=SALE_Y&productFilterType=APP
# lg https://web.joongna.com/search?category=1195&saleYn=SALE_Y&page={page}&productFilterType=APP
# 기타 https://web.joongna.com/search?category=1196&saleYn=SALE_Y&page=125&productFilterType=APP

In [8]:
# Initialize the WebDriver
#driver = webdriver.Chrome()

def getElementText(xpath):
    return driver.find_element(By.XPATH, xpath).text

# # url 불러오기
# driver = webdriver.Chrome()
# url = (f"https://web.joongna.com/search?category=1193&saleYn=SALE_Y&page={i}&productFilterType=APP")
# driver.get(url)

In [13]:
driver = webdriver.Chrome()

df = pd.DataFrame(columns=['Title', 'Link'])

data = []

# Loop through pages 39 to 104
for page in range(53, 126):
    url = f"https://web.joongna.com/search?category=1196&saleYn=SALE_Y&page={page}&productFilterType=APP"
    driver.get(url)
    
    # Wait for the page to load completely
    time.sleep(2)
    
    # Loop through items on the page
    for i in range(1, 87):
        try:
            # Find the element using a dynamic CSS selector
            wrapper = driver.find_element(By.CSS_SELECTOR, f'li:nth-child({i}) > div > div > a')
#__next > div > main > div.mx-auto.px-4.md\:px-8.\32 xl\:px-16.box-content.pt-0.pb-16.bg-white.lg\:pt-\[72px\].lg\:pb-20.max-w-\[1024px\].min-\[1600px\]\:max-w-\[1280px\] > div > ul > li:nth-child(3) > div > div > a
            # Extract the title and link attributes
            title = wrapper.get_attribute('title')
            link = wrapper.get_attribute('href')

            # Append each title and link to the data list
            data.append({'Title': title, 'Link': link})
            
        except Exception as e:
            print(f"Error occurred on page {page}, item {i}: {str(e)}")
            continue

# Convert the list to a DataFrame
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('/Users/jiyoonkim/Desktop/labtop_etc.csv', index=False)

# Close the WebDriver
driver.quit()

Error occurred on page 53, item 4: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(4) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 53, item 12: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(12) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 53, item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 53, item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 53, item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 53, item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 4: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(4) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 12: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(12) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812
6   chromedriver                        0x000000010293f9ec chromedriver + 506348
7   chromedriver                        0x0000000102ca6510 chromedriver + 4072720
8   chromedriver                        0x0000000102caafbc chromedriver + 4091836
9   chromedriver                        0x0000000102c8d754 chromedriver + 3970900
10  chromedriver                        0x0000000102cab8a4 chromedriver + 4094116
11  chromedriver                        0x0000000102c806d4 chromedriver + 3917524
12  chromedriver                        0x0000000102cc8b08 chromedriver + 4213512
13  chromedriver                        0x0000000102cc8c84 chromedriver + 4213892
14  chromedriver                        0x0000000102cd6a08 chromedriver + 4270600
15  libsystem_pthread.dylib             0x000000018de8b034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018de85e3c thread_start + 8

Error occurred on page 54, item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > div > a"}
  (Session info: chrome=125.0.6422.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x0000000102cde4c8 chromedriver + 4302024
1   chromedriver                        0x0000000102cd6e10 chromedriver + 4271632
2   chromedriver                        0x000000010290819c chromedriver + 278940
3   chromedriver                        0x000000010294a2c4 chromedriver + 549572
4   chromedriver                        0x0000000102982c5c chromedriver + 781404
5   chromedriver                        0x000000010293f004 chromedriver + 503812

In [14]:
df

,Title,Link
0,아수스 젠북14 ux425ea-ki207,https://web.joongna.com/product/157684833
1,델 15,https://web.joongna.com/product/157682880
2,델 래티튜드5590노트북,https://web.joongna.com/product/141606687
3,한성컴퓨터 -TFX 255s 노트북,https://web.joongna.com/product/157448015
4,플립북 무선 14인치,https://web.joongna.com/product/157676456
...,...,...
5835,RTX 2060 게이밍 노트북 TFG7476H 팝니다,https://web.joongna.com/product/111460487
5836,"msi 게이밍 노트북 (GTX1660ti,240hz)",https://web.joongna.com/product/111940265
5837,윈도우10 한글 MS오피스 설치 i5 ACER 노트북,https://web.joongna.com/product/110255037
5838,"A8 hp노트북 파빌리온g6 15"" 램10 ssd128",https://web.joongna.com/product/102126142
5839,마이크로소프트 서피스 2022 랩탑 스튜디오 미개봉 판,https://web.joongna.com/product/110105278

In [10]:
# //*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[1]/a
# //*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[3]/a
# //*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[5]/a
# //*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[7]/a

SyntaxError: invalid syntax (4217316195.py, line 1)

In [ ]:
# for i in range(1, 87):
#     f'//*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[{i}]/a'

In [3]:
def getElementText(xpath):
    return driver.find_element(By.XPATH, xpath).text

# url 불러오기
driver = webdriver.Chrome()
panre_url = "https://web.joongna.com/search?category=6&page=1"
driver.get(panre_url)

time.sleep(2)

# "판매완료 상품포함" 클릭 적용

btn_selled = driver.find_element(By.XPATH, '//*[@id="__next"]/div/main/div[1]/div/div[1]/table/tbody/tr[3]/td[2]/ul/li[2]/label')
btn_selled.click()

time.sleep(2)

In [12]:
df = pd.DataFrame(columns=['Title', 'Link'])
df

Empty DataFrame
Columns: [Title, Link]
Index: []

In [40]:
df = pd.DataFrame(columns=['Title', 'Link'])

data = []

for i in range(1, 87):
    try:
        # Find the element using a dynamic CSS selector
        wrapper = driver.find_element(By.CSS_SELECTOR, f'li:nth-child({i}) > div > a')

        # Extract the title and link attributes
        title = wrapper.get_attribute('title')
        link = wrapper.get_attribute('href')

        # 리스트에 각각의 title과 link를 추가
        data.append({'Title': title, 'Link': link})
        
        # 2초 대기
        #time.sleep(1)
        
    except Exception as e:
        print(f"Error occurred for item {i}: {str(e)}")
        continue

df = pd.DataFrame(data)

Error occurred for item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001030e441c chromedriver + 4326428
1   chromedriver                        0x00000001030dc8e4 chromedriver + 4294884
2   chromedriver                        0x0000000102d08088 chromedriver + 278664
3   chromedriver                        0x0000000102d4aa80 chromedriver + 551552
4   chromedriver                        0x0000000102d834f8 chromedriver + 783608
5   chromedriver                        0x0000000102d3f4e4 chromedriver + 505060
6   chromedriver                        0x0000000102d3ff5c chromedriver + 507740
7   chromedriver                        0x00000001030a79b8 chromedriver + 4078008
8   chromedriver                        0x00000001030ac770 chromedriver + 4097904
9   chromedriver                        0x000000010308e55c chromedriver + 3974492
10  chromedriver                        0x00000001030ad088 chromedriver + 4100232
11  chromedriver                        0x000000010307fb4c chromedriver + 3914572
12  chromedriver                        0x00000001030cd690 chromedriver + 4232848
13  chromedriver                        0x00000001030cd80c chromedriver + 4233228
14  chromedriver                        0x00000001030dc558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001030e441c chromedriver + 4326428
1   chromedriver                        0x00000001030dc8e4 chromedriver + 4294884
2   chromedriver                        0x0000000102d08088 chromedriver + 278664
3   chromedriver                        0x0000000102d4aa80 chromedriver + 551552
4   chromedriver                        0x0000000102d834f8 chromedriver + 783608
5   chromedriver                        0x0000000102d3f4e4 chromedriver + 505060
6   chromedriver                        0x0000000102d3ff5c chromedriver + 507740
7   chromedriver                        0x00000001030a79b8 chromedriver + 4078008
8   chromedriver                        0x00000001030ac770 chromedriver + 4097904
9   chromedriver                        0x000000010308e55c chromedriver + 3974492
10  chromedriver                        0x00000001030ad088 chromedriver + 4100232
11  chromedriver                        0x000000010307fb4c chromedriver + 3914572
12  chromedriver                        0x00000001030cd690 chromedriver + 4232848
13  chromedriver                        0x00000001030cd80c chromedriver + 4233228
14  chromedriver                        0x00000001030dc558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001030e441c chromedriver + 4326428
1   chromedriver                        0x00000001030dc8e4 chromedriver + 4294884
2   chromedriver                        0x0000000102d08088 chromedriver + 278664
3   chromedriver                        0x0000000102d4aa80 chromedriver + 551552
4   chromedriver                        0x0000000102d834f8 chromedriver + 783608
5   chromedriver                        0x0000000102d3f4e4 chromedriver + 505060
6   chromedriver                        0x0000000102d3ff5c chromedriver + 507740
7   chromedriver                        0x00000001030a79b8 chromedriver + 4078008
8   chromedriver                        0x00000001030ac770 chromedriver + 4097904
9   chromedriver                        0x000000010308e55c chromedriver + 3974492
10  chromedriver                        0x00000001030ad088 chromedriver + 4100232
11  chromedriver                        0x000000010307fb4c chromedriver + 3914572
12  chromedriver                        0x00000001030cd690 chromedriver + 4232848
13  chromedriver                        0x00000001030cd80c chromedriver + 4233228
14  chromedriver                        0x00000001030dc558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x00000001030e441c chromedriver + 4326428
1   chromedriver                        0x00000001030dc8e4 chromedriver + 4294884
2   chromedriver                        0x0000000102d08088 chromedriver + 278664
3   chromedriver                        0x0000000102d4aa80 chromedriver + 551552
4   chromedriver                        0x0000000102d834f8 chromedriver + 783608
5   chromedriver                        0x0000000102d3f4e4 chromedriver + 505060
6   chromedriver                        0x0000000102d3ff5c chromedriver + 507740
7   chromedriver                        0x00000001030a79b8 chromedriver + 4078008
8   chromedriver                        0x00000001030ac770 chromedriver + 4097904
9   chromedriver                        0x000000010308e55c chromedriver + 3974492
10  chromedriver                        0x00000001030ad088 chromedriver + 4100232
11  chromedriver                        0x000000010307fb4c chromedriver + 3914572
12  chromedriver                        0x00000001030cd690 chromedriver + 4232848
13  chromedriver                        0x00000001030cd80c chromedriver + 4233228
14  chromedriver                        0x00000001030dc558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

In [ ]:
https://web.joongna.com/search?category=1193&saleYn=SALE_Y&page=39&productFilterType=APP

In [13]:
import time

data = []

for j in range(3, 6):  # 예를 들어, 5번의 페이지 이동을 수행한다고 가정합니다.
    for i in range(1, 87):
        try:
            # Find the element using a dynamic CSS selector
            wrapper = driver.find_element(By.CSS_SELECTOR, f'li:nth-child({i}) > div > a')

            # Extract the title and link attributes
            title = wrapper.get_attribute('title')
            link = wrapper.get_attribute('href')

            # 리스트에 각각의 title과 link를 추가
            data.append({'Title': title, 'Link': link})
            
            # 2초 대기
            #time.sleep(2)
            
        except Exception as e:
            print(f"Error occurred for item {i}: {str(e)}")
            continue
    #time.sleep(2)
    # 페이지를 넘어가기 위해 '다음' 버튼 클릭
    try:
        btn_nxt = driver.find_element(By.XPATH, f'//*[@id="__next"]/div/main/div[1]/div/div[4]/ul/li[{j}]/a')  # 다음 버튼 XPATH
        btn_nxt.click()
        time.sleep(3)  # 페이지 로드를 위해 충분한 시간 대기

    except Exception as e:
        print(f"Error occurred while clicking next button: {str(e)}")
        break  # 다음 버튼이 없거나 클릭할 수 없을 때 루프 종료

# 리스트를 DataFrame으로 변환
df = pd.DataFrame(data)

Error occurred for item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 20: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(20) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 28: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(28) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 36: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(36) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008
8   chromedriver                        0x00000001032d4770 chromedriver + 4097904
9   chromedriver                        0x00000001032b655c chromedriver + 3974492
10  chromedriver                        0x00000001032d5088 chromedriver + 4100232
11  chromedriver                        0x00000001032a7b4c chromedriver + 3914572
12  chromedriver                        0x00000001032f5690 chromedriver + 4232848
13  chromedriver                        0x00000001032f580c chromedriver + 4233228
14  chromedriver                        0x0000000103304558 chromedriver + 4293976
15  libsystem_pthread.dylib             0x0000000189597034 _pthread_start + 136
16  libsystem_pthread.dylib             0x0000000189591e3c thread_start + 8

Error occurred for item 44: Message: no such element: Unable to locate element: {"method":"css selector","selector":"li:nth-child(44) > div > a"}
  (Session info: chrome=123.0.6312.87); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010330c41c chromedriver + 4326428
1   chromedriver                        0x00000001033048e4 chromedriver + 4294884
2   chromedriver                        0x0000000102f30088 chromedriver + 278664
3   chromedriver                        0x0000000102f72a80 chromedriver + 551552
4   chromedriver                        0x0000000102fab4f8 chromedriver + 783608
5   chromedriver                        0x0000000102f674e4 chromedriver + 505060
6   chromedriver                        0x0000000102f67f5c chromedriver + 507740
7   chromedriver                        0x00000001032cf9b8 chromedriver + 4078008

In [14]:
df

,Title,Link
0,핸드폰 그립톡거치대 새상품(메탈블랙),https://web.joongna.com/product/161055177
1,아이패드프로 12.9 6세대 M2실버 와이파이+셀룰러,https://web.joongna.com/product/160445674
2,아이폰 15프로 티타늄블랙 256G 판매합니다,https://web.joongna.com/product/161914072
3,,https://adcr.naver.com/adcr?x=iSihtsRWIPcuFpxk...
4,아이패드 프로 10.5 512GB 로즈골드 (s급외관),https://web.joongna.com/product/161854373
...,...,...
241,(미개봉) 갤럭시탭S8 울트라 와이파이 256GB 판매합니다,https://web.joongna.com/product/161909879
242,아이폰15프로 256G 미개봉+추가Full(영수증유),https://web.joongna.com/product/161154302
243,갤럭시Z플립5 512G 민트 박스풀셋,https://web.joongna.com/product/161162970
244,아이폰 급속충전기 정품 20w c타입(어탭터+케이블),https://web.joongna.com/product/160751046
245,아이폰 xs max 512기가 화이트 S급 팝니다,https://web.joongna.com/product/161909838

In [17]:
a = getElementText('//*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[3]/a')
a

'모바일/태블릿'

In [ ]:
#1, 3, 5, 7, 9
f'//*[@id="__next"]/div/main/div[1]/div[1]/div[2]/div[1]/ol/li[{i}]/a'

In [ ]:
try:
    # 이미지 요소를 찾기 위해 CSS 선택자 사용
    image_element = driver.find_element(By.CSS_SELECTOR, '#__next > div > main > div.mx-auto.md\:px-8.\32 xl\:px-16.box-content.max-w-\[1024px\].min-\[1600px\]\:max-w-\[1280px\].lg\:min-h-\[950px\].px-5 > div.items-start.block.grid-cols-2.lg\:grid.gap-x-\[72px\].lg\:pt-\[72px\].lg\:pb-\[52px\].pb-9.pt-0 > div.carouselWrapper.relative.product-gallery.swiperThumbnail.product-gallery-slider.dotsCircle > div > div.swiper-wrapper > div.swiper-slide.swiper-slide-active > div > img')
    
    # 이미지의 src 속성 가져오기
    image_src = image_element.get_attribute('src')
    
    # 이미지 다운로드 요청
    response = requests.get(image_src)
    
    # 이미지 저장 폴더 생성
    os.makedirs('images', exist_ok=True)
    
    # 이미지 파일 경로 설정
    image_filename = 'images/image1.jpg'  # 파일명은 원하는 대로 수정 가능합니다.
    
    # 이미지 파일 저장
    with open(image_filename, 'wb') as f:
        f.write(response.content)
    
    print("Image downloaded successfully:", image_filename)
    
except Exception as e:
    print("Error occurred while downloading image:", str(e))

In [ ]:
import time

# 각 링크를 방문하기 위한 루프
for link in df['Link']:
    try:
        # 새 탭에서 링크 열기
        driver.execute_script("window.open('');")
        driver.switch_to.window(driver.window_handles[-1])  # 새로운 탭으로 이동
        driver.get(link)
        
        # 페이지가 로드될 때까지 기다리기
        time.sleep(2)
        
        # 여기서 필요한 작업 수행
        
        # 탭 닫기
        driver.close()
        
        # 원래 탭으로 돌아가기
        driver.switch_to.window(driver.window_handles[0])
        
    except Exception as e:
        print(f"Error occurred while visiting link {link}: {str(e)}")
        continue

In [18]:
wrapper = driver.find_element(By.CSS_SELECTOR, 'li:nth-child(86) > div > a')
title = wrapper.get_attribute('title')
link = wrapper.get_attribute('href')
print(title)
print(link)

Z플립 케이스 ㅡ 새상품
https://web.joongna.com/product/161560982

In [10]:
real_id_l = []

elements = [x.get_attribute('id') for x in driver.find_elements(By.CSS_SELECTOR, 'tbody#areaList > tr dd.layer_popup > dl')]
real_id_l.extend(elements)

# 첫번째 페이지에서 두번째 페이지 넘어가는 버튼 누르기
move_btn = driver.find_element(By.XPATH, '//*[@id="tabwrap"]/div/div/div[1]/div[3]/div/fieldset/p/a/img')
move_btn.click()
time.sleep(3)

while True:
    # 현재 페이지의 id 추출
    elements1 = [x.get_attribute('id') for x in driver.find_elements(By.CSS_SELECTOR, 'tbody#areaList > tr dd.layer_popup > dl')]
    real_id_l.extend(elements1)

    # 다음 페이지로 이동
    try:
        #두번째 이후 페이지부터 누르는 버튼
        move_btn2 = driver.find_element(By.XPATH, '//*[@id="tabwrap"]/div/div/div[1]/div[3]/div/fieldset/p/a[2]/img')
        move_btn2.click()
        time.sleep(2)
    except NoSuchElementException:
        break

In [11]:
len(real_id_l)

783

In [18]:
#숫자만 추출하기 위해 dl_ 제거

real_id_l2 = [x.strip("dl_") for x in real_id_l]
real_id_l2

['3296250',
 '3296245',
 '3296249',
 '3295673',
 '3295675',
 '3295676',
 '3295678',
 '3295683',
 '3294976',
 '3294985',
 '3294988',
 '3294990',
 '3294991',
 '3294995',
 '3294671',
 '3294674',
 '3294676',
 '3294677',
 '3294137',
 '3294155',
 '3294156',
 '3294142',
 '3293085',
 '3293086',
 '3293087',
 '3293071',
 '3293079',
 '3293080',
 '3292284',
 '3292269',
 '3292271',
 '3292277',
 '3292279',
 '3292285',
 '3291888',
 '3291897',
 '3291898',
 '3291899',
 '3291911',
 '3291914',
 '3291904',
 '3291909',
 '3291194',
 '3291196',
 '3291197',
 '3291199',
 '3288434',
 '3288437',
 '3288441',
 '3288442',
 '3283285',
 '3283291',
 '3283293',
 '3283283',
 '3282959',
 '3282965',
 '3282963',
 '3282964',
 '3282709',
 '3282724',
 '3282717',
 '3282713',
 '3282715',
 '3282250',
 '3282257',
 '3282245',
 '3282247',
 '3281854',
 '3281846',
 '3281847',
 '3281868',
 '3281711',
 '3281713',
 '3281715',
 '3281695',
 '3281716',
 '3281699',
 '3281719',
 '3280620',
 '3280623',
 '3280646',
 '3280638',
 '3280648',
 '3276708',
 '3276719',
 '3276716',
 '3276717',
 '3276718',
 '3275940',
 '3275924',
 '3275934',
 '3275925',
 '3275926',
 '3275937',
 '3275939',
 '3275030',
 '3275010',
 '3275024',
 '3275016',
 '3275028',
 '3274654',
 '3274666',
 '3274658',
 '3274649',
 '3274250',
 '3274251',
 '3274261',
 '3274243',
 '3274258',
 '3274112',
 '3274103',
 '3274116',
 '3274118',
 '3273796',
 '3273809',
 '3273805',
 '3273196',
 '3273197',
 '3273101',
 '3273092',
 '3272501',
 '3272503',
 '3272516',
 '3272507',
 '3271821',
 '3271823',
 '3271809',
 '3271814',
 '3271755',
 '3271757',
 '3271685',
 '3271690',
 '3271311',
 '3271302',
 '3271307',
 '3270366',
 '3269476',
 '3269469',
 '3266501',
 '3266507',
 '3266180',
 '3266186',
 '3266188',
 '3266189',
 '3265508',
 '3264740',
 '3264744',
 '3264754',
 '3264755',
 '3264746',
 '3264757',
 '3264758',
 '3264413',
 '3264364',
 '3264365',
 '3264366',
 '3263436',
 '3263447',
 '3263448',
 '3262912',
 '3262909',
 '3262904',
 '3262918',
 '3262894',
 '3262901',
 '3261491',
 '3261487',
 '3261187',
 '3260501',
 '3260505',
 '3260515',
 '3260509',
 '3259696',
 '3259689',
 '3259692',
 '3259276',
 '3259288',
 '3259282',
 '3259303',
 '3258950',
 '3258956',
 '3258946',
 '3258444',
 '3258454',
 '3258447',
 '3257640',
 '3257642',
 '3257637',
 '3257643',
 '3249902',
 '3249556',
 '3249549',
 '3248730',
 '3248729',
 '3247582',
 '3247583',
 '3247579',
 '3247589',
 '3245882',
 '3245883',
 '3245876',
 '3245877',
 '3245881',
 '3245878',
 '3245868',
 '3245869',
 '3245864',
 '3245865',
 '3245867',
 '3245863',
 '3245866',
 '3245861',
 '3245862',
 '3245820',
 '3245859',
 '3245860',
 '3245858',
 '3239942',
 '3239934',
 '3239944',
 '3239946',
 '3239949',
 '3239930',
 '3239926',
 '3239927',
 '3239928',
 '3239929',
 '3239542',
 '3239543',
 '3239544',
 '3239526',
 '3239539',
 '3239795',
 '3239797',
 '3239800',
 '3239789',
 '3236546',
 '3236537',
 '3236539',
 '3236543',
 '3236549',
 '3236540',
 '3236544',
 '3236536',
 '3236548',
 '3236521',
 '3236523',
 '3236525',
 '3236510',
 '3236511',
 '3236526',
 '3236471',
 '3236472',
 '3236465',
 '3236456',
 '3236458',
 '3236468',
 '3233251',
 '3233242',
 '3233244',
 '3233237',
 '3233238',
 '3233248',
 '3233239',
 '3232910',
 '3232901',
 '3232911',
 '3232908',
 '3232896',
 '3232897',
 '3232891',
 '3232362',
 '3232368',
 '3232359',
 '3232363',
 '3232355',
 '3232349',
 '3232343',
 '3232346',
 '3228753',
 '3228757',
 '3228748',
 '3228761',
 '3228764',
 '3228765',
 '3228768',
 '3228622',
 '3228625',
 '3228634',
 '3228630',
 '3228632',
 '3228659',
 '3228650',
 '3228654',
 '3228658',
 '3228656',
 '3225698',
 '3225702',
 '3225703',
 '3225699',
 '3225690',
 '3225710',
 '3225707',
 '3225689',
 '3225709',
 '3224650',
 '3224641',
 '3224639',
 '3224640',
 '3222892',
 '3222885',
 '3222889',
 '3222883',
 '3219088',
 '3219092',
 '3219104',
 '3219095',
 '3217701',
 '3217703',
 '3217697',
 '3216954',
 '3216959',
 '3218670',
 '3218672',
 '3218673',
 '3218674',
 '3218658',
 '3214243',
 '3214248',
 '3214240',
 '3213801',
 '3213797',
 '3213807',
 '3212893',
 '3212894',
 '3212885',
 '3212898',
 '3212895',
 '3212899',
 '3212219',
 '3212223',
 '3212217',
 '3211562',
 '3211563',
 '3211558',
 '3210894',
 '3210885',
 '3210886',
 '3210888',
 '3210482',
 '3210474',
 '3210476',
 '3210472',
 '3210478',
 '3209497',
 '3209499',
 '3209500',
 '3208872',
 '3208870',
 '3208873',
 '3207945',
 '3207944',
 '3207947',
 '3207949',
 '3207431',
 '3207429',
 '3207424',
 '3207425',
 '3206838',
 '3206840',
 '3206836',
 '3206837',
 '3206293',
 '3206287',
 '3206288',
 '3206299',
 '3205942',
 '3205934',
 '3205937',
 '3205931',
 '3205374',
 '3205375',
 '3205376',
 '3204242',
 '3204321',
 '3204322',
 '3204244',
 '3204318',
 '3204310',
 '3204301',
 '3204312',
 '3204257',
 '3204265',
 '3204306',
 '3204267',
 '3204279',
 '3204293',
 '3204284',
 '3204290',
 '3200673',
 '3200671',
 '3200674',
 '3200675',
 '3200676',
 '3200100',
 '3200092',
 '3200096',
 '3200090',
 '3200102',
 '2380439',
 '2380460',
 '2380458',
 '2380192',
 '2380196',
 '2380205',
 '2258655',
 '2255820',
 '2255812',
 '2255827',
 '2255816',
 '2255724',
 '2255716',
 '2255720',
 '2255722',
 '2255719',
 '2255541',
 '2255523',
 '2255534',
 '2255551',
 '2254662',
 '2254672',
 '2254678',
 '2254302',
 '2254293',
 '2254299',
 '2254301',
 '2252831',
 '2252834',
 '2252847',
 '2252651',
 '2252642',
 '2252643',
 '2252638',
 '2252382',
 '2252397',
 '2252388',
 '2252389',
 '2251933',
 '2251919',
 '2251920',
 '2251446',
 '2251456',
 '2251443',
 '2249353',
 '2249364',
 '2249365',
 '2248840',
 '2248846',
 '2248849',
 '2247900',
 '2247907',
 '2247916',
 '2246473',
 '2246465',
 '2246469',
 '2246460',
 '2246162',
 '2246154',
 '2246164',
 '2245871',
 '2245881',
 '2245867',
 '2245145',
 '2245138',
 '2245129',
 '2244308',
 '2244331',
 '2244317',
 '2239942',
 '2239925',
 '2239926',
 '2235421',
 '2235408',
 '2235418',
 '2235171',
 '2235161',
 '2235159',
 '2233100',
 '2233110',
 '2233106',
 '2232614',
 '2232605',
 '2232619',
 '2232100',
 '2232090',
 '2232084',
 '2231833',
 '2231857',
 '2231852',
 '2231510',
 '2231512',
 '2231506',
 '2229951',
 '2229946',
 '2229971',
 '2229119',
 '2229151',
 '2229144',
 '2228905',
 '2228897',
 '2228899',
 '2228245',
 '2228265',
 '2228255',
 '2228170',
 '2228168',
 '2228175',
 '2226500',
 '2226497',
 '2226509',
 '2226261',
 '2226255',
 '2226256',
 '2225644',
 '2225654',
 '2225645',
 '2225192',
 '2225175',
 '2225188',
 '2224619',
 '2224609',
 '2224598',
 '2223741',
 '2223759',
 '2223749',
 '2222951',
 '2222955',
 '2222959',
 '2222140',
 '2222120',
 '2222128',
 '2218640',
 '2218653',
 '2218649',
 '2218134',
 '2218136',
 '2218125',
 '2217130',
 '2217119',
 '2217118',
 '2216214',
 '2216215',
 '2216212',
 '2214214',
 '2214213',
 '2212406',
 '2212398',
 '2212393',
 '2208710',
 '2208722',
 '2208732',
 '2208353',
 '2208333',
 '2208346',
 '2205017',
 '2205028',
 '2205015',
 '2203732',
 '2203726',
 '2203724',
 '2202834',
 '2202826',
 '2202833',
 '2201530',
 '2201526',
 '2201539',
 '2200046',
 '2200048',
 '2200010',
 '2200011',
 '2200012',
 '2197481',
 '2197473',
 '2197478',
 '2196475',
 '2196476',
 '2196477',
 '2195662',
 '2195675',
 '2195676',
 '2195351',
 '2195337',
 '2195347',
 '2194612',
 '2194608',
 '2194609',
 '2194103',
 '2194105',
 '2194107',
 '2193642',
 '2193643',
 '2193644',
 '2192314',
 '2192317',
 '2192328',
 '2190262',
 '2190272',
 '2190268',
 '2187613',
 '2187606',
 '2185820',
 '2185830',
 '2184520',
 '2184512',
 '2184527',
 '2184537',
 '2184208',
 '2184194',
 '2184199',
 '2179241',
 '2179249',
 '2178983',
 '2178977',
 '2178572',
 '2178577',
 '2178195',
 '2178196',
 '2178199',
 '2177040',
 '2177032',
 '2177023',
 '2176055',
 '2176064',
 '2175587',
 '2175589',
 '2175045',
 '2175047',
 '2174811',
 '2174814',
 '2174815',
 '2174371',
 '2174372',
 '2174366',
 '2174159',
 '2173010',
 '2173021',
 '2173024',
 '2172585',
 '2172579',
 '2172156',
 '2172588',
 '2172148',
 '2172144',
 '2170376',
 '2170387',
 '2170377',
 '2170111',
 '2170105',
 '2169342',
 '2169354',
 '2168851',
 '2168849',
 '2164011',
 '2164014',
 '2164017',
 '2154115',
 '2153345',
 '2153133',
 '2153146',
 '2152863',
 '2152844',
 '2146828',
 '2146829',
 '2146830',
 '2145312',
 '2143219',
 '2140475',
 '2140485',
 '2138794',
 '2138795',
 '2138046',
 '2135973',
 '2134628',
 '2132394',
 '2132396',
 '2132397',
 '2133819',
 '2131462',
 '2131096',
 '2129559',
 '2129459',
 '2129449',
 '2124100',
 '2124114',
 '2059604',
 '2058832',
 '1985372',
 '2061655',
 '2060846',
 '2060053',
 '2064333',
 '2063876',
 '2063351',
 '2060160',
 '2060174',
 '2060378',
 '1984246',
 '2063452',
 '2063453',
 '2062738',
 '2064766',
 '2064767',
 '2058901',
 '2061966',
 '2060132',
 '2059119',
 '1986053',
 '1986047',
 '2061373',
 '1984517',
 '1982908',
 '1982866',
 '2060240',
 '2060227',
 '1979845',
 '2059437',
 '1979232',
 '1980695',
 '2060678',
 '2060679',
 '1980678',
 '2059891',
 '1981707',
 '1981889',
 '1981336',
 '1981330',
 '1982283',
 '1982397',
 '1982443',
 '1982385',
 '2062510',
 '2065016',
 '2062509',
 '2059792',
 '2059776',
 '1982097',
 '2058957',
 '1982091',
 '2061773',
 '2061766',
 '1982191',
 '1979009',
 '1979230',
 '1979008',
 '2061743',
 '1979005',
 '2061759',
 '1981250',
 '2060962',
 '2060960',
 '2060747',
 '2060958',
 '2067607',
 '1980080',
 '2067613',
 '2067595',
 '2067605',
 '1979931',
 '2067162',
 '2067591',
 '2067155',
 '2066997',
 '2066614',
 '1981315',
 '1983349',
 '1982812',
 '1983336',
 '1982816',
 '2066093',
 '1982258',
 '1981683',
 '2065683',
 '1982814']

In [13]:
# 페이지별로 접속하며 데이터 전부 긁어오기

panre_tit_list = []
panre_subt_list = []
panre_info_list =[]
fails = []

for i in real_id_l2:
    try:
        driver.get(f'''https://glaw.scourt.go.kr/wsjo/panre/sjo100.do?contId={i}''')
        time.sleep(5)
        panre_tit_list.append(getElementText('//*[@id="bmunStart"]/h2'))
        panre_subt_list.append(getElementText('//*[@id="bmunStart"]/p'))
        panre_info_list.append(driver.find_element(By.CSS_SELECTOR, 'div.page').text)
        time.sleep(3)
    except Exception as e:
        fails.append(i)
        continue

In [14]:
# 긁어온 데이터 수 확인
len(panre_tit_list)

783

In [16]:
# 긁어온 데이터 csv로 저장

df_1 = pd.DataFrame({
    "tit": panre_tit_list,
    "sub_tit": panre_subt_list,
    "info_1": panre_info_list
})

df_1

df_1.to_csv("/Users/jiyoonkim/Desktop/대학원/23-1 연구/대법원 판례 데이터 크롤링/info_2.csv")

In [21]:
#긁어온 데이터 csv파일 불러오기
data = pd.read_csv("/Users/jiyoonkim/Desktop/대학원/23-1 연구/대법원 판례 데이터 크롤링/info_2.csv")
data

,Unnamed: 0,tit,sub_tit,info_1
0,0,대법원 2023. 3. 13. 선고 2020두53545 판결,[현역의지위확인등청구의소]〈군인사법상 계급별 연령정년의 연장 여부에 대한 사건〉[공...,"【판시사항】\n군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익..."
1,1,대법원 2023. 3. 9. 선고 2022도16120 판결,[실화]〈담배꽁초를 버린 공동의 과실이 경합되어 공장에 화재가 발생한 경우 각자 실...,【판시사항】\n[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이...
2,2,대법원 2023. 3. 9. 선고 2020다218925 판결,[손해배상(의)]〈미성년자인 환자에 대한 진료 과실 등으로 병원에 손해배상을 구하는...,【판시사항】\n[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해...
3,3,대법원 2023. 2. 23. 선고 2022두57381 판결,[업무정지처분취소]〈개업공인중개사가 서명 및 날인하여야 하는 중개대상물 확인·설명서...,"【판시사항】\n[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령..."
4,4,대법원 2023. 2. 23.자 2022모2092 결정,[잠정조치기각결정에대한재항고]〈검사가 「스토킹범죄의 처벌 등에 관한 법률」(이하 ‘...,"【판시사항】\n기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우,..."
...,...,...,...,...
778,778,대법원 2007. 7. 19. 선고 2006두19297 전원합의체 판결,"[임원취임승인취소처분]〈경기학원임시이사사건〉[집55(2)특,508;공2007.8.1...",【판시사항】\n[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임...
779,779,서울중앙지법 2007. 7. 13. 선고 2006나16757 판결,[손해배상(지)] 확정〈“바람의 나라” 및 “태왕사신기” 사건〉[각공2007.9.1...,【판시사항】\n[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의...
780,780,서울중앙지법 2007. 7. 6. 선고 2006가합22413 판결,[정보게시금지등] 항소〈로마켓 변호사 승소율 제공 사건〉[각공2007.8.10.(4...,【판시사항】\n[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민...
781,781,대법원 2007. 6. 28. 선고 2004다54282 판결,"[손해배상(기)]〈한강조망이익침해사건〉[집55(1)민,299;공2007.8.1.(2...",【판시사항】\n[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망...
782,782,서울가법 2007. 6. 22. 선고 2004드단77721 판결,"[이혼] 확정〈북한이탈주민 이혼소송〉[각공2007.10.10.(50),2168]","【판시사항】\n북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두..."

In [22]:
# 추가 인덱스 column drop

data = data.drop(data.columns[0], axis = 1)
data

,tit,sub_tit,info_1
0,대법원 2023. 3. 13. 선고 2020두53545 판결,[현역의지위확인등청구의소]〈군인사법상 계급별 연령정년의 연장 여부에 대한 사건〉[공...,"【판시사항】\n군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익..."
1,대법원 2023. 3. 9. 선고 2022도16120 판결,[실화]〈담배꽁초를 버린 공동의 과실이 경합되어 공장에 화재가 발생한 경우 각자 실...,【판시사항】\n[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이...
2,대법원 2023. 3. 9. 선고 2020다218925 판결,[손해배상(의)]〈미성년자인 환자에 대한 진료 과실 등으로 병원에 손해배상을 구하는...,【판시사항】\n[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해...
3,대법원 2023. 2. 23. 선고 2022두57381 판결,[업무정지처분취소]〈개업공인중개사가 서명 및 날인하여야 하는 중개대상물 확인·설명서...,"【판시사항】\n[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령..."
4,대법원 2023. 2. 23.자 2022모2092 결정,[잠정조치기각결정에대한재항고]〈검사가 「스토킹범죄의 처벌 등에 관한 법률」(이하 ‘...,"【판시사항】\n기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우,..."
...,...,...,...
778,대법원 2007. 7. 19. 선고 2006두19297 전원합의체 판결,"[임원취임승인취소처분]〈경기학원임시이사사건〉[집55(2)특,508;공2007.8.1...",【판시사항】\n[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임...
779,서울중앙지법 2007. 7. 13. 선고 2006나16757 판결,[손해배상(지)] 확정〈“바람의 나라” 및 “태왕사신기” 사건〉[각공2007.9.1...,【판시사항】\n[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의...
780,서울중앙지법 2007. 7. 6. 선고 2006가합22413 판결,[정보게시금지등] 항소〈로마켓 변호사 승소율 제공 사건〉[각공2007.8.10.(4...,【판시사항】\n[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민...
781,대법원 2007. 6. 28. 선고 2004다54282 판결,"[손해배상(기)]〈한강조망이익침해사건〉[집55(1)민,299;공2007.8.1.(2...",【판시사항】\n[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망...
782,서울가법 2007. 6. 22. 선고 2004드단77721 판결,"[이혼] 확정〈북한이탈주민 이혼소송〉[각공2007.10.10.(50),2168]","【판시사항】\n북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두..."

In [37]:
# title 분리

new_df = pd.DataFrame(columns=['기관', '선고 날짜', '판결문번호', '분류', '선고명', '공고번호'])

for i in range(len(data)):
    text = data.loc[i, 'tit']
    if '선고' in text:
        part1_and_2, part3= text.split(" 선고 ")
        part12 = part1_and_2.split(" ")
        part1 = part12[0]
        part2 = " ".join(part12[1:])
        new_df.loc[i, '기관'] = part1.strip()
        new_df.loc[i, '선고 날짜'] = part2.strip()
        new_df.loc[i, '판결문번호'] = part3.strip(" 판결")
    elif '자' in text:
        part1_and_2, part3= text.split("자")
        part12 = part1_and_2.split(" ")
        part1 = part12[0]
        part2 = " ".join(part12[1:])
        new_df.loc[i, '기관'] = part1.strip()
        new_df.loc[i, '선고 날짜'] = part2.strip()
        new_df.loc[i, '판결문번호'] = part3.strip(" 결정")
    else:
        new_df.loc[i, '기관'] = text.strip()

In [38]:
new_df

         기관         선고 날짜             판결문번호   분류  선고명 공고번호
0       대법원  2023. 3. 13.        2020두53545  NaN  NaN  NaN
1       대법원   2023. 3. 9.        2022도16120  NaN  NaN  NaN
2       대법원   2023. 3. 9.       2020다218925  NaN  NaN  NaN
3       대법원  2023. 2. 23.        2022두57381  NaN  NaN  NaN
4       대법원  2023. 2. 23.         2022모2092  NaN  NaN  NaN
..      ...           ...               ...  ...  ...  ...
778     대법원  2007. 7. 19.  2006두19297 전원합의체  NaN  NaN  NaN
779  서울중앙지법  2007. 7. 13.        2006나16757  NaN  NaN  NaN
780  서울중앙지법   2007. 7. 6.       2006가합22413  NaN  NaN  NaN
781     대법원  2007. 6. 28.        2004다54282  NaN  NaN  NaN
782    서울가법  2007. 6. 22.       2004드단77721  NaN  NaN  NaN

[783 rows x 6 columns]

In [40]:
# sub_title 분리

for i in range(len(data)):
    text = data.loc[i, 'sub_tit']
    if '〈' in text:
        part1, part2_and_3 = text.split("〈")
        part2, part3 = part2_and_3.split("〉")
        new_df.loc[i, '분류'] = re.sub(r'[\[\]]', '', part1)
        new_df.loc[i, '선고명'] = part2.strip()
        new_df.loc[i, '공고번호'] = re.sub(r'[\[\]]', '', part3)
    elif '][' in text:
        part1, part2 = text.split("][")
        new_df.loc[i, '분류'] = re.sub(r'[\[\]]', '', part1)
        new_df.loc[i, '공고번호'] = re.sub(r'[\[\]]', '', part2)
    else:
        new_df.loc[i, '분류'] = text.strip()

In [42]:
new_df

,기관,선고 날짜,판결문번호,분류,선고명,공고번호
0,대법원,2023. 3. 13.,2020두53545,현역의지위확인등청구의소,군인사법상 계급별 연령정년의 연장 여부에 대한 사건,"공2023상,672"
1,대법원,2023. 3. 9.,2022도16120,실화,담배꽁초를 버린 공동의 과실이 경합되어 공장에 화재가 발생한 경우 각자 실화죄의 책...,"공2023상,680"
2,대법원,2023. 3. 9.,2020다218925,손해배상(의),미성년자인 환자에 대한 진료 과실 등으로 병원에 손해배상을 구하는 사건,"공2023상,645"
3,대법원,2023. 2. 23.,2022두57381,업무정지처분취소,개업공인중개사가 서명 및 날인하여야 하는 중개대상물 확인·설명서의 의미가 문제된 사건,"공2023상,616"
4,대법원,2023. 2. 23.,2022모2092,잠정조치기각결정에대한재항고,검사가 「스토킹범죄의 처벌 등에 관한 법률」(이하 ‘스토킹처벌법’이라고 한다) 제9...,"공2023상,640"
...,...,...,...,...,...,...
778,대법원,2007. 7. 19.,2006두19297 전원합의체,임원취임승인취소처분,경기학원임시이사사건,"집55(2)특,508;공2007.8.15.(280),1291"
779,서울중앙지법,2007. 7. 13.,2006나16757,손해배상(지) 확정,“바람의 나라” 및 “태왕사신기” 사건,"각공2007.9.10.(49),1925"
780,서울중앙지법,2007. 7. 6.,2006가합22413,정보게시금지등 항소,로마켓 변호사 승소율 제공 사건,"각공2007.8.10.(48),1590"
781,대법원,2007. 6. 28.,2004다54282,손해배상(기),한강조망이익침해사건,"집55(1)민,299;공2007.8.1.(279),1135"
782,서울가법,2007. 6. 22.,2004드단77721,이혼 확정,북한이탈주민 이혼소송,"각공2007.10.10.(50),2168"

In [43]:
# 본문 분류 작업 전 [전문] 기준으로 나누기

new_df2 = pd.DataFrame(columns=['part1', 'part2'])

for i in range (len(data)):
    text = data.loc[i, 'info_1']
    part1, part2 = text.split('【전 문】')
    new_df2.loc[i, 'part1'] = part1.strip()
    new_df2.loc[i, 'part2'] = part2.strip()

In [44]:
new_df2

,part1,part2
0,"【판시사항】\n군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익...","【원고, 상고인】 원고 (소송대리인 법무법인 저스티스 담당변호사 도현택 외 5인)\..."
1,【판시사항】\n[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이...,【피 고 인】 피고인 1 외 1인\n【상 고 인】 피고인들\n【변 호 인】 변호사 ...
2,【판시사항】\n[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해...,"【원고, 상고인 겸 피상고인】 원고 1(미성년자이므로 법정대리인 친권자 부 ○○○,..."
3,"【판시사항】\n[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령...","【원고, 상고인】 원고 (소송대리인 법무법인 송정 담당변호사 서한규)\n【피고, 피..."
4,"【판시사항】\n기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우,...",【스토킹행위자】 스토킹행위자\n【재항고인】 검사\n【원심결정】 대구지법 2022. ...
...,...,...
778,【판시사항】\n[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임...,"【원고, 상고인】 원고 1외 4인 (소송대리인 변호사 진종백)\n【피고, 피상고인】..."
779,【판시사항】\n[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의...,"【원고, 항소인】 원고 (소송대리인 법무법인 바른 담당변호사 오승종)\n【피고, 피..."
780,【판시사항】\n[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민...,【원고(선정당사자)】 원고(선정당사자) (소송대리인 법무법인 일촌 담당변호사 이백수...
781,【판시사항】\n[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망...,"【원고, 상고인 겸 피상고인】 원고 1외 17인\n【원고(탈퇴)】 원고 19\n【원..."
782,"【판시사항】\n북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두...",【원 고】 원고\n【피 고】 피고\n【변론종결】\n2007. 6. 1.\n【주 문】...

In [50]:
new_df3 = pd.DataFrame(columns=['판시사항', '판결요지', '참조조문', '참조판례', '전 문', '주 문', '이 유'])

for i in range(len(data)):
    text = new_df2.loc[i, 'part1']
    if "\n【판결요지】\n" in text:
        part1, part2_3_4 = text.split("\n【판결요지】\n")
        if '【참조조문】' in part2_3_4:
            part2, part3_4 = part2_3_4.split("\n【참조조문】\n")
            if '【참조판례】' in part3_4:
                part3, part4 = part3_4.split("\n【참조판례】\n")
                new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')
                new_df3.loc[i, '판결요지'] = part2.strip()
                new_df3.loc[i, '참조조문'] = part3.strip()
                new_df3.loc[i, '참조판례'] = part4.strip()
            else:
                part3 = part3_4
                new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')
                new_df3.loc[i, '판결요지'] = part2.strip()
                new_df3.loc[i, '참조조문'] = part3.strip()
        else:
            new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')
            new_df3.loc[i, '판결요지'] = part2_3_4.strip()
    else:
        part1, part2_3_4 = text.split("\n【결정요지】\n")
        if '【참조조문】' in part2_3_4:
            part2, part3_4 = part2_3_4.split("\n【참조조문】\n")
            if '【참조판례】' in part3_4:
                part3, part4 = part3_4.split("\n【참조판례】\n")
                new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')
                new_df3.loc[i, '판결요지'] = part2.strip()
                new_df3.loc[i, '참조조문'] = part3.strip()
                new_df3.loc[i, '참조판례'] = part4.strip()
            else:
                part3 = part3_4
                new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')
                new_df3.loc[i, '판결요지'] = part2.strip()
                new_df3.loc[i, '참조조문'] = part3.strip()
        else:
            new_df3.loc[i, '판시사항'] = part1.strip('【판시사항】\n')

In [51]:
new_df3

,판시사항,판결요지,참조조문,참조판례,전 문,주 문,이 유
0,"군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익처분이 확정판결...",대법원은 구 국가정보원직원법(2003. 12. 30. 법률 제7012호로 개정되기 ...,"헌법 제7조 제2항, 군인사법 제8조 제1항","대법원 2007. 2. 8. 선고 2005두7273 판결(공2007상, 442)",NaN,NaN,NaN
1,[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이 경합되어 화재...,[1] 형법이 금지하고 있는 법익침해의 결과발생을 방지할 법적인 작위의무를 지고 있...,"[1] 형법 제18조, 제170조 [2] 형법 제18조, 제170조 제1항","[1] 대법원 1983. 5. 10. 선고 82도2279 판결(공1983, 983)...",NaN,NaN,NaN
2,[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해서 의료행위에 ...,[1] 의사는 응급환자의 경우나 그 밖에 특별한 사정이 없는 한 환자에게 수술 등 ...,"[1] 의료법 제24조의2, 민법 제750조 [2] 의료법 제24조의2 제1항, 제...","[1] 대법원 1994. 4. 15. 선고 93다60953 판결(공1994상, 14...",NaN,NaN,NaN
3,"[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령(=처분 시 시...",[1] 행정처분은 근거 법령이 개정된 경우에도 경과규정에서 달리 정함이 없는 한 처...,[1] 행정소송법 제1조[행정처분일반] [2] 구 공인중개사법(2018. 8. 14...,"[1] 대법원 2010. 3. 11. 선고 2008두15169 판결(공2010상, ...",NaN,NaN,NaN
4,"기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우, 그 기간의 연...","스토킹범죄의 처벌 등에 관한 법률(이하 ‘스토킹처벌법’이라고 한다)의 입법 목적, ...","스토킹범죄의 처벌 등에 관한 법률 제2조, 제8조 제1항, 제9조 제1항, 제5항,...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
778,[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임시까지 종전 직...,"[1] 학교법인의 이사나 감사 전원 또는 그 일부의 임기가 만료되었다고 하더라도, ...",[1] 구 사립학교법(2005. 12. 29. 법률 제7802호로 개정되기 전의 것...,"[1][2] 대법원 1963. 4. 25. 선고 63다15 판결(집11-1민, 26...",NaN,NaN,NaN
779,[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의거관계가 추인되...,[1] A 저작자가 B 저작자의 저작물에 대한 저작권을 침해하였다고 하기 위하여는 ...,"[1] 저작권법 제10조 [2] 저작권법 제2조 제1호, 제10조 [3] 저작권법 ...","[2] 대법원 1997. 9. 29.자 97마330 결정(공1997하, 3374)\...",NaN,NaN,NaN
780,[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민의 ‘알 권리’...,"[1] 헌법 제10조, 제17조의 규정은 개인의 사생활이 타인에 의해 침해되거나 함...","[1] 헌법 제10조, 제17조 [2] 헌법 제10조, 제17조, 제21조 [3] ...","[1] 대법원 1998. 7. 24. 선고 96다42789 판결(공1998하, 22...",NaN,NaN,NaN
781,[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망이익의 침해행위...,[1] 어느 토지나 건물의 소유자가 종전부터 향유하고 있던 경관이나 조망이 그에게 ...,"[1] 헌법 제35조, 민법 제750조 [2] 민법 제2조, 제750조 [3] 민법...",[1][2][5] 대법원 2004. 9. 13. 선고 2003다64602 판결(공2...,NaN,NaN,NaN
782,"북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","민법 제840조 제6호, 북한이탈주민의 보호 및 정착지원에 관한 법률 제19조의2 ...",NaN,NaN,NaN,NaN

In [60]:
for i in range(len(data)):
    text = new_df2.loc[i, 'part2']
    if '【주 문】' in text:
        part1, part2_3_4 = text.split("\n【주 문】\n")
        if "【이 유】" in part2_3_4:
            part2, part3_4 = part2_3_4.split("\n【이 유】\n")
            new_df3.loc[i, '전 문'] = part1.strip()
            new_df3.loc[i, '주 문'] = part2.strip()
            new_df3.loc[i, '이 유'] = part3_4.strip()
            #new_df3.loc[i, '참조판례'] = part4.strip()
        else:
            new_df3.loc[i, '전 문'] = part1.strip()
            new_df3.loc[i, '주 문'] = part2_3_4.strip()
    else: 
        new_df3.loc[i, '전 문'] = text.strip()

In [61]:
new_df3

,판시사항,판결요지,참조조문,참조판례,전 문,주 문,이 유
0,"군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익처분이 확정판결...",대법원은 구 국가정보원직원법(2003. 12. 30. 법률 제7012호로 개정되기 ...,"헌법 제7조 제2항, 군인사법 제8조 제1항","대법원 2007. 2. 8. 선고 2005두7273 판결(공2007상, 442)","【원고, 상고인】 원고 (소송대리인 법무법인 저스티스 담당변호사 도현택 외 5인)\...",원고의 주위적 청구에 관한 상고를 기각한다. 원심판결 중 예비적 청구에 관한 부분을...,상고이유를 판단한다.\n1. 주위적 청구에 관하여\n이 사건 정년 전역명령을 받을 ...
1,[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이 경합되어 화재...,[1] 형법이 금지하고 있는 법익침해의 결과발생을 방지할 법적인 작위의무를 지고 있...,"[1] 형법 제18조, 제170조 [2] 형법 제18조, 제170조 제1항","[1] 대법원 1983. 5. 10. 선고 82도2279 판결(공1983, 983)...",【피 고 인】 피고인 1 외 1인\n【상 고 인】 피고인들\n【변 호 인】 변호사 ...,상고를 모두 기각한다.,상고이유를 판단한다.\n형법이 금지하고 있는 법익침해의 결과발생을 방지할 법적인 작...
2,[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해서 의료행위에 ...,[1] 의사는 응급환자의 경우나 그 밖에 특별한 사정이 없는 한 환자에게 수술 등 ...,"[1] 의료법 제24조의2, 민법 제750조 [2] 의료법 제24조의2 제1항, 제...","[1] 대법원 1994. 4. 15. 선고 93다60953 판결(공1994상, 14...","【원고, 상고인 겸 피상고인】 원고 1(미성년자이므로 법정대리인 친권자 부 ○○○,...","원심판결 중 피고 패소 부분을 파기하고, 이 부분 사건을 서울고등법원에 환송한다. ...",상고이유를 판단한다.\n1. 사건의 개요\n원심판결 이유와 기록에 의하면 다음 사실...
3,"[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령(=처분 시 시...",[1] 행정처분은 근거 법령이 개정된 경우에도 경과규정에서 달리 정함이 없는 한 처...,[1] 행정소송법 제1조[행정처분일반] [2] 구 공인중개사법(2018. 8. 14...,"[1] 대법원 2010. 3. 11. 선고 2008두15169 판결(공2010상, ...","【원고, 상고인】 원고 (소송대리인 법무법인 송정 담당변호사 서한규)\n【피고, 피...","원심판결을 파기하고, 사건을 대구고등법원에 환송한다.","상고이유를 판단한다.\n1. 사안의 개요\n원심판결 이유와 기록에 의하면, 다음과 ..."
4,"기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우, 그 기간의 연...","스토킹범죄의 처벌 등에 관한 법률(이하 ‘스토킹처벌법’이라고 한다)의 입법 목적, ...","스토킹범죄의 처벌 등에 관한 법률 제2조, 제8조 제1항, 제9조 제1항, 제5항,...",NaN,【스토킹행위자】 스토킹행위자\n【재항고인】 검사\n【원심결정】 대구지법 2022. ...,"원심결정을 파기하고, 사건을 대구지방법원에 환송한다.",재항고이유를 판단한다.\n1. 스토킹범죄에 대한 잠정조치 관련 법리\n가. 1) 스...
...,...,...,...,...,...,...,...
778,[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임시까지 종전 직...,"[1] 학교법인의 이사나 감사 전원 또는 그 일부의 임기가 만료되었다고 하더라도, ...",[1] 구 사립학교법(2005. 12. 29. 법률 제7802호로 개정되기 전의 것...,"[1][2] 대법원 1963. 4. 25. 선고 63다15 판결(집11-1민, 26...","【원고, 상고인】 원고 1외 4인 (소송대리인 변호사 진종백)\n【피고, 피상고인】...",상고를 모두 기각한다. 상고비용은 원고들이 부담한다.,"1. 먼저 직권으로 판단한다.\n가. 원심판결 이유와 기록에 의하면, 피고는 200..."
779,[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의거관계가 추인되...,[1] A 저작자가 B 저작자의 저작물에 대한 저작권을 침해하였다고 하기 위하여는 ...,"[1] 저작권법 제10조 [2] 저작권법 제2조 제1호, 제10조 [3] 저작권법 ...","[2] 대법원 1997. 9. 29.자 97마330 결정(공1997하, 3374)\...","【원고, 항소인】 원고 (소송대리인 법무법인 바른 담당변호사 오승종)\n【피고, 피...",1. 원고의 항소를 기각한다.\n2. 항소비용은 원고가 부담한다.\n【청구취지 및 ...,1. 원고의 만화 ‘바람의 나라’ 집필과 피고의 시놉시스 ‘태왕사신기’의 발표\n다...
780,[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민의 ‘알 권리’...,"[1] 헌법 제10조, 제17조의 규정은 개인의 사생활이 타인에 의해 침해되거나 함...","[1] 헌법 제10조, 제17조 [2] 헌법 제10조, 제17조, 제21조 [3] ...","[1] 대법원 1998. 7. 24. 선고 96다42789 판결(공1998하, 22...",【원고(선정당사자)】 원고(선정당사자) (소송대리인 법무법인 일촌 담당변호사 이백수...,1. 피고는 인터넷 홈페이지 “(인터넷 주소 생략 )”에서 원고(선정당사자) 및 선...,"1. 기초 사실\n다음의 사실은 당사자 사이에 다툼이 없거나, 갑 제1 내지 3호증..."
781,[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망이익의 침해행위...,[1] 어느 토지나 건물의 소유자가 종전부터 향유하고 있던 경관이나 조망이 그에게 ...,"[1] 헌법 제35조, 민법 제750조 [2] 민법 제2조, 제750조 [3] 민법...",[1][2][5] 대법원 2004. 9. 13. 선고 2003다64602 판결(공2...,"【원고, 상고인 겸 피상고인】 원고 1외 17인\n【원고(탈퇴)】 원고 19\n【원...","원심판결 중 원고 1, 원고 4, 원고 7을 제외한 나머지 원고들 및 원고 19의 ...","1. 피고 1 주식회사의 상고이유 제1, 2점과 피고 2 주식회사의 상고이유 제1,..."
782,"북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","민법 제840조 제6호, 북한이탈주민의 보호 및 정착지원에 관한 법률 제19조의2 ...",NaN,【원 고】 원고\n【피 고】 피고\n【변론종결】\n2007. 6. 1.,1. 원고와 피고는 이혼한다.\n2. 소송비용은 피고가 부담한다.\n【청구취지】\n...,1. 기초 사실\n갑 제1 내지 4호증(가지번호 포함)의 각 기재에 변론 전체의 취...

In [62]:
final = pd.concat([new_df, new_df3], axis = 1)
final

,기관,선고 날짜,판결문번호,분류,선고명,공고번호,판시사항,판결요지,참조조문,참조판례,전 문,주 문,이 유
0,대법원,2023. 3. 13.,2020두53545,현역의지위확인등청구의소,군인사법상 계급별 연령정년의 연장 여부에 대한 사건,"공2023상,672","군인이 임용권자로부터 받은 파면 등 징계, 전역명령 등 신분상 불이익처분이 확정판결...",대법원은 구 국가정보원직원법(2003. 12. 30. 법률 제7012호로 개정되기 ...,"헌법 제7조 제2항, 군인사법 제8조 제1항","대법원 2007. 2. 8. 선고 2005두7273 판결(공2007상, 442)","【원고, 상고인】 원고 (소송대리인 법무법인 저스티스 담당변호사 도현택 외 5인)\...",원고의 주위적 청구에 관한 상고를 기각한다. 원심판결 중 예비적 청구에 관한 부분을...,상고이유를 판단한다.\n1. 주위적 청구에 관하여\n이 사건 정년 전역명령을 받을 ...
1,대법원,2023. 3. 9.,2022도16120,실화,담배꽁초를 버린 공동의 과실이 경합되어 공장에 화재가 발생한 경우 각자 실화죄의 책...,"공2023상,680",[1] 형법상 부작위범의 성립 요건 / 실화죄에 있어서 공동의 과실이 경합되어 화재...,[1] 형법이 금지하고 있는 법익침해의 결과발생을 방지할 법적인 작위의무를 지고 있...,"[1] 형법 제18조, 제170조 [2] 형법 제18조, 제170조 제1항","[1] 대법원 1983. 5. 10. 선고 82도2279 판결(공1983, 983)...",【피 고 인】 피고인 1 외 1인\n【상 고 인】 피고인들\n【변 호 인】 변호사 ...,상고를 모두 기각한다.,상고이유를 판단한다.\n형법이 금지하고 있는 법익침해의 결과발생을 방지할 법적인 작...
2,대법원,2023. 3. 9.,2020다218925,손해배상(의),미성년자인 환자에 대한 진료 과실 등으로 병원에 손해배상을 구하는 사건,"공2023상,645",[1] 의사의 설명의무의 내용\n[2] 의사가 미성년자인 환자에 대해서 의료행위에 ...,[1] 의사는 응급환자의 경우나 그 밖에 특별한 사정이 없는 한 환자에게 수술 등 ...,"[1] 의료법 제24조의2, 민법 제750조 [2] 의료법 제24조의2 제1항, 제...","[1] 대법원 1994. 4. 15. 선고 93다60953 판결(공1994상, 14...","【원고, 상고인 겸 피상고인】 원고 1(미성년자이므로 법정대리인 친권자 부 ○○○,...","원심판결 중 피고 패소 부분을 파기하고, 이 부분 사건을 서울고등법원에 환송한다. ...",상고이유를 판단한다.\n1. 사건의 개요\n원심판결 이유와 기록에 의하면 다음 사실...
3,대법원,2023. 2. 23.,2022두57381,업무정지처분취소,개업공인중개사가 서명 및 날인하여야 하는 중개대상물 확인·설명서의 의미가 문제된 사건,"공2023상,616","[1] 행정처분의 근거 법령이 개정된 경우, 행정처분에 적용되는 법령(=처분 시 시...",[1] 행정처분은 근거 법령이 개정된 경우에도 경과규정에서 달리 정함이 없는 한 처...,[1] 행정소송법 제1조[행정처분일반] [2] 구 공인중개사법(2018. 8. 14...,"[1] 대법원 2010. 3. 11. 선고 2008두15169 판결(공2010상, ...","【원고, 상고인】 원고 (소송대리인 법무법인 송정 담당변호사 서한규)\n【피고, 피...","원심판결을 파기하고, 사건을 대구고등법원에 환송한다.","상고이유를 판단한다.\n1. 사안의 개요\n원심판결 이유와 기록에 의하면, 다음과 ..."
4,대법원,2023. 2. 23.,2022모2092,잠정조치기각결정에대한재항고,검사가 「스토킹범죄의 처벌 등에 관한 법률」(이하 ‘스토킹처벌법’이라고 한다) 제9...,"공2023상,640","기간이 정하여져 있으나 연장이 가능한 접근금지 잠정조치 결정의 경우, 그 기간의 연...","스토킹범죄의 처벌 등에 관한 법률(이하 ‘스토킹처벌법’이라고 한다)의 입법 목적, ...","스토킹범죄의 처벌 등에 관한 법률 제2조, 제8조 제1항, 제9조 제1항, 제5항,...",NaN,【스토킹행위자】 스토킹행위자\n【재항고인】 검사\n【원심결정】 대구지법 2022. ...,"원심결정을 파기하고, 사건을 대구지방법원에 환송한다.",재항고이유를 판단한다.\n1. 스토킹범죄에 대한 잠정조치 관련 법리\n가. 1) 스...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,대법원,2007. 7. 19.,2006두19297 전원합의체,임원취임승인취소처분,경기학원임시이사사건,"집55(2)특,508;공2007.8.15.(280),1291",[1] 임기가 만료된 학교법인의 이사나 감사가 후임이사나 감사의 선임시까지 종전 직...,"[1] 학교법인의 이사나 감사 전원 또는 그 일부의 임기가 만료되었다고 하더라도, ...",[1] 구 사립학교법(2005. 12. 29. 법률 제7802호로 개정되기 전의 것...,"[1][2] 대법원 1963. 4. 25. 선고 63다15 판결(집11-1민, 26...","【원고, 상고인】 원고 1외 4인 (소송대리인 변호사 진종백)\n【피고, 피상고인】...",상고를 모두 기각한다. 상고비용은 원고들이 부담한다.,"1. 먼저 직권으로 판단한다.\n가. 원심판결 이유와 기록에 의하면, 피고는 200..."
779,서울중앙지법,2007. 7. 13.,2006나16757,손해배상(지) 확정,“바람의 나라” 및 “태왕사신기” 사건,"각공2007.9.10.(49),1925",[1] 저작권 침해가 인정되기 위한 요건 및 그 주관적 요건으로서 의거관계가 추인되...,[1] A 저작자가 B 저작자의 저작물에 대한 저작권을 침해하였다고 하기 위하여는 ...,"[1] 저작권법 제10조 [2] 저작권법 제2조 제1호, 제10조 [3] 저작권법 ...","[2] 대법원 1997. 9. 29.자 97마330 결정(공1997하, 3374)\...","【원고, 항소인】 원고 (소송대리인 법무법인 바른 담당변호사 오승종)\n【피고, 피...",1. 원고의 항소를 기각한다.\n2. 항소비용은 원고가 부담한다.\n【청구취지 및 ...,1. 원고의 만화 ‘바람의 나라’ 집필과 피고의 시놉시스 ‘태왕사신기’의 발표\n다...
780,서울중앙지법,2007. 7. 6.,2006가합22413,정보게시금지등 항소,로마켓 변호사 승소율 제공 사건,"각공2007.8.10.(48),1590",[1] 헌법상 보장되는 자기정보통제권의 범위\n[2] 개인정보가 국민의 ‘알 권리’...,"[1] 헌법 제10조, 제17조의 규정은 개인의 사생활이 타인에 의해 침해되거나 함...","[1] 헌법 제10조, 제17조 [2] 헌법 제10조, 제17조, 제21조 [3] ...","[1] 대법원 1998. 7. 24. 선고 96다42789 판결(공1998하, 22...",【원고(선정당사자)】 원고(선정당사자) (소송대리인 법무법인 일촌 담당변호사 이백수...,1. 피고는 인터넷 홈페이지 “(인터넷 주소 생략 )”에서 원고(선정당사자) 및 선...,"1. 기초 사실\n다음의 사실은 당사자 사이에 다툼이 없거나, 갑 제1 내지 3호증..."
781,대법원,2007. 6. 28.,2004다54282,손해배상(기),한강조망이익침해사건,"집55(1)민,299;공2007.8.1.(279),1135",[1] 조망이익이 법적인 보호의 대상이 되기 위한 요건\n[2] 조망이익의 침해행위...,[1] 어느 토지나 건물의 소유자가 종전부터 향유하고 있던 경관이나 조망이 그에게 ...,"[1] 헌법 제35조, 민법 제750조 [2] 민법 제2조, 제750조 [3] 민법...",[1][2][5] 대법원 2004. 9. 13. 선고 2003다64602 판결(공2...,"【원고, 상고인 겸 피상고인】 원고 1외 17인\n【원고(탈퇴)】 원고 19\n【원...","원심판결 중 원고 1, 원고 4, 원고 7을 제외한 나머지 원고들 및 원고 19의 ...","1. 피고 1 주식회사의 상고이유 제1, 2점과 피고 2 주식회사의 상고이유 제1,..."
782,서울가법,2007. 6. 22.,2004드단77721,이혼 확정,북한이탈주민 이혼소송,"각공2007.10.10.(50),2168","북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","북한이탈주민의 혼인생활이 이미 북한에서도 파탄에 이르렀고, 북한에 두고 온 배우자가...","민법 제840조 제6호, 북한이탈주민의 보호 및 정착지원에 관한 법률 제19조의2 ...",NaN,【원 고】 원고\n【피 고】 피고\n【변론종결】\n2007. 6. 1.,1. 원고와 피고는 이혼한다.\n2. 소송비용은 피고가 부담한다.\n【청구취지】\n...,1. 기초 사실\n갑 제1 내지 4호증(가지번호 포함)의 각 기재에 변론 전체의 취...

In [63]:
final.to_csv("/Users/jiyoonkim/Desktop/대학원/23-1 연구/대법원 판례 데이터 크롤링/panre_final.csv")